Todoproject/Todoproject/TodoApp/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.Home,name='home'),
    path('form/',views.Form,name='form'),
    path('details/<int:id>',views.Details,name='details'),
    path('update/<int:id>',views.Update,name='update'),
    path('delete/<int:id>',views.Delete,name='delete'),
    
]

Todoproject/Todoproject/Todoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('TodoApp.urls')),
    path('auth/',include('userarauth.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Todoproject/Todoproject/userarauth/urls.py
from django.urls import path
from.import views

app_name='auth'
urlpatterns = [
    path('register/',views.registerUser,name='register'),
    path('login/',views.loginUser,name='login'),
    path('logoutuser/',views.logoutUser,name='logout'),
    
    
    
]

Todoproject/Todoproject/TodoApp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=30)
    rate=models.FloatField()
    screen=models.CharField(max_length=5)
    language=models.CharField(max_length=30)
    duration=models.CharField(max_length=10)
    category=models.CharField(max_length=15)
    certification=models.CharField(max_length=5)
    date=models.DateField()
    image=models.ImageField(upload_to='todoimage')
    banner=models.ImageField(upload_to='todoimage')
    description=models.CharField(max_length=200)

    
    def __str__(self):
        return self.name

Todoproject/Todoproject/userarauth/models.py
from django.db import models

# Create your models here.

Todoproject/Todoproject/TodoApp/forms.py
from .models import Movie
from django import forms  

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields='__all__'

Todoproject/Todoproject/TodoApp/views.py
from django.shortcuts import render,redirect
from .models import Movie
from .forms import MovieForm

def Home(req):
    movies=Movie.objects.all()
    return render(req,'index.html',{'movies':movies})




def Form(req):
    if req.method=="POST": 
        
        name=req.POST.get('name','')
        rate=req.POST.get('rate','')
        screen=req.POST.get('screen','')
        language=req.POST.get('language','')
        duration=req.POST.get('duration','')
        category=req.POST.get('category','')
        certification=req.POST.get('certification','')
        date=req.POST.get('date','')
        image=req.FILES['image']
        banner=req.FILES['banner']
        description=req.POST.get('description','')        
        movie=Movie(name=name,rate=rate,screen=screen,language=language,duration=duration,category=category,certification=certification,date=date,image=image,banner=banner,description=description)
        movie.save()
        return redirect('home')
    return render(req,'form.html')



def Details(req,id):
    movies=Movie.objects.get(id=id)
        
        
    
    return render(req,'details.html',{'movies':movies})


def Update(req,id):
    movies=Movie.objects.get(id=id)
    # if req.method=="POST": 
        
    #     name=req.POST.get('name','')
    #     rate=req.POST.get('rate','')
    #     screen=req.POST.get('screen','')
    #     language=req.POST.get('language','')
    #     duration=req.POST.get('duration','')
    #     category=req.POST.get('category','')
    #     certification=req.POST.get('certification','')
    #     date=req.POST.get('date','')
    #     image=req.FILES['image']
    #     banner=req.FILES['banner']
    #     description=req.POST.get('description','')        
    #     Movie.objects.filter(id=id).update(name=name,rate=rate,screen=screen,language=language,duration=duration,category=category,certification=certification,date=date,image=image,banner=banner,description=description)
    #     return redirect('home')
    f=MovieForm(req.POST,req.FILES or None,instance=movies)
    if f.is_valid():
        f.save()
        return redirect('home')
    return render(req,'formUpdate.html',{"movies":movies,'f':f})

def Delete(req,id):
    movies=Movie.objects.get(id=id)
    if req.method=="POST":
        Movie.objects.filter(id=id).delete()
        return redirect('home')
    return render(req,'delete.html',{"movies":movies})

Todoproject/Todoproject/userarauth/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib import auth

# Create your views here.

def registerUser(req):
    if req.method=='POST':
        fname=req.POST.get("fname","")
        lname=req.POST.get("lname","")
        email=req.POST.get("email","")
        username=req.POST.get("username","")
        password=req.POST.get("password","")
        cpassword=req.POST.get("cpassword","")
        print(fname,lname,email,username,password,cpassword)
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(req,"username already exist")
                return redirect('auth:register')
            elif User.objects.filter(email=email).exists():
                messages.info(req,"email already exist")
                return redirect('auth:register')
            else:
                user=User.objects.create_user(first_name=fname,last_name=lname,email=email,username=username,password=password)
                user.save()
                return redirect('auth:login')
        else:
            messages.info(req,"password not matched")
            return redirect('auth:register')
    return render(req, 'registeruser.html')
def loginUser(req):
    if req.method=='POST':
        username=req.POST.get("username","")
        password=req.POST.get("password","")
        user=auth.authenticate(username=username,password=password)
        print(user)
        if user is not None:
          auth.login(req,user)
          return redirect("home")
        else:
            messages.info(req, "invalidcredentials")
            return redirect('auth:login')
    return render(req, 'loginuser.html')




def logoutUser(req):
    auth.logout(req)
    return redirect("home")
    
    
            
 

Todoproject/Todoproject/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bootstrap demo</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css\index.css' %}">
  <link rel="stylesheet" href="{% static 'css\style.css' %}">
</head>

<body>
  {% include 'nav.html' %}
  {% block content %}

  {% endblock %}
  {% include 'footer.html'%}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    crossorigin="anonymous"></script>
</body>

</html>

Todoproject/Todoproject/templates/delete.html
{% extends 'base.html' %}
    {% block content %}
<div class="container">
    <div class="row">
        <div class="d-flex justisfy-content-center">
            <form action="" method="post" class="form w-50">
                {% csrf_token %}
                <div class="my-3">
                    <h1>DO YOU WANT TO DELETE?</h1>
                </div>
                <div class="my-3 text-center mx-0">
                    <button class="btn btn-primary">Delete</button>
                </div>
            </form>
        </div>
    </div>
 </div>   
{% endblock %}

Todoproject/Todoproject/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid ">
    <img class="ii banner " src="{{ movies.banner.url }}" alt="Background Image">

    <div class="card-slot row py-5 ">

        <!-- imagecard -->
        <div class=" col-6  col-md-2 cardsss ">
            <img class="card-img-top rounded-3" src="{{ movies.image.url }}" alt="Card image cap">
        </div>
        <!-- moviename -->
        <div class="col ps-2 p-3">
            <div class="row text-light">
                <h1>{{ movies.name }}</h1>
            </div>
            <!-- rating -->
            <div class="row ">
                <div class="col-6 text-light starrate">
                    <h5><svg xmlns="http://www.w3.org/2000/svg" height="20" width="22.5"
                            viewBox="0 0 576 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
                            <path fill="#FFD43B"
                                d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z" />
                        </svg>

                    </h5>
                </div>
                <div class="col-3 raterate text-light">
                    <h3><b>{{ movies.rate }}</b></h3>
                </div>
                <div class="col-3 text-light votes">
                    <h6><b>145.1k Votes ></b></h6>
                </div>
            </div>
            <!-- ratenow -->
            <div class="row ratingreview text-light  ">
                <div class="col-9">
                    <h6>Add your rating & review<br> </h6>
                    <p class="m-0">Your ratings matter</p>
                </div>
                <div class="col-3">
                    <button type="button" class="btn btn-light text-dark ">Rate now</button>
                </div>
            </div>
            <div class="row text-dark mt-3 ">
                <div class="col-1 screentype rounded ms-0 px-2 text-center bg-light">{{ movies.screen }}</div>
                <div class="col-1 screentype rounded ms-2 p-x-2 text-center bg-light">{{ movies.language }}</div>
            </div>
            <div class="row">
                <div class="col mt-2 ms-1 text-light">
                    <h6>{{movies.duration}} • {{movies.category}} • {{movies.certification}} • {{ movies.date }}</h6>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <a href="/update/{{movies.id}}" class="btn btn-success ms-2 mt-3 px-5  text-light  ">update</a>
                    <a href="/delete/{{movies.id}}" class="btn btn-danger ms-2 mt-3 px-5  text-light  ">delete</a>
                </div>
            </div>

        </div>

    </div>
</div>



{% endblock %}

Todoproject/Todoproject/templates/footer.html
{% comment %} <nav class="navbar bg-dark navbar-dark">
    <div class="container-fluid">
      <span class="navbar-brand mb-0 mx-auto h1">footer</span>
    </div>
  </nav>
   {% endcomment %}

Todoproject/Todoproject/templates/form.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <form class="border mt-5 mb-2" method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <input class="form-control mb-2" type="text" name="name" placeholder="Movie name">

        <input class="form-control mb-2" type="number" name="rate" placeholder="Rate">

        <input class="form-control mb-2" type="text" name="screen" placeholder="Screen">

        <input class="form-control mb-2" type="text" name="language" placeholder="Language">

        <input class="form-control mb-2" type="text" name="duration" placeholder="Duration">

        <input class="form-control mb-2" type="text" name="category" placeholder="Category">

        <input class="form-control mb-2" type="text" name="certification" placeholder="certification">

        <input class="form-control mb-2" type="date" name="date" placeholder="Releas date">

        <input class="form-control mb-2" type="file" name="image" placeholder="Poster">

        <input class="form-control mb-2" type="file" name="banner" placeholder="Banner">

        <input class="form-control mb-2" type="text" name="description" placeholder="Description">
        
        <button class="btn btn-success mb-3 mt-3" style="margin-left: 450px;">ADD</button>
    </form>
  
</div>



{% endblock %}

Todoproject/Todoproject/templates/formUpdate.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{f.as_p}}
    <input type="submit" value="Update">
</form>
{% endblock %}

Todoproject/Todoproject/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load static %}
<div id="carouselExampleIndicators" class="carousel slide carouselbackgroundcolor" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
      aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
      aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
      aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item px-4 py-2  active">
      <img src="{% static './image/img1.jpg' %}" class="d-block w-100 rounded-3" alt="...">
    </div>
    <div class="carousel-item px-4 py-2">
      <img src="{% static './image/img2.jpg' %}" class="d-block w-100 rounded-3" alt="...">
    </div>
    <div class="carousel-item px-4 py-2 ">
      <img src="{% static './image/img3.jpg' %}" class="d-block w-100 rounded-3" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>



<h2 class="recommended_movies">Recommended Movie</h2>
<div class="card-slot row ps-4">
  {% for movie in movies %}
  <div class=" col-6  col-md-2 cardsss ">
    <a href="/details/{{movie.id}}">
      <img class="card-img-top rounded-3" src="{{movie.image.url}}" alt="Card image cap">
    </a>
    <div class="card-body ">
      <h5 class="card-title ps-1 ">{{ movie.name }}</h5>
      <p class="card-text ps-1 ">{{ movie.category }}</p>

    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

Todoproject/Todoproject/templates/loginuser.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}

    <div>
        <input type="text" placeholder="username" name="username">
    </div>
    <div>
        <input type="text" placeholder="password" name="password">
    </div>
    <div>
        <button>login</button>
    </div>
</form>

{% endblock %}

Todoproject/Todoproject/templates/nav.html
{% load static %}

<div class="c">
  <nav class="navbar firstnavbar navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand firstnav-brand ms-5" href="{% url 'home' %}"><img src="{% static './image/book1.jpg' %}"
          alt=""></a>
      <div class="d-flex">
        <input class="form-control search_bar me-1" type="search"
          placeholder="     Search for Movies, Events, Plays, Sports and Activities" aria-label="Search">
      </div>
      <a href="{% url 'form' %}" class="btn btn-success btnn_add_movies mt-1 btn-sm">ADD Movie</a>
      {% if user.is_authenticated %}
      <span>{{user}}</span>
      <a href="{% url 'auth:logout' %}" class="btn btn-danger me-2" type="submit">logout</a>
      {% else %}
      <a href="{% url 'auth:register' %}" class="btn btn-danger me-2" type="submit">sign in</a>
      {% endif %}
      

      <button class="btn btn-light me-2" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight"
        aria-controls="offcanvasRight"><span class="navbar-toggler-icon"></span>
      </button>

      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
        <div class="offcanvas-header">
          <h3 id="offcanvasRightLabel">Hey!</h3>
          <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close">
          </button>
        </div>
        <div class="offcanvas-body">
          <h2>fff</h2>
        </div>
      </div>
    </div>
  </nav>

  <div class="row">
    <div class="col-12 p-0">
      <nav class="navbar secondnavbar navbar-expand-lg navbar-light ">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item ps-4">
                <a class="nav-link  active" aria-current="page" href="#">Movies</a>
              </li>
              <li class="nav-item ">
                <a class="nav-link active" href="#"> Stream</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="#">Events</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active ">Plays</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active "> Sports</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active ">Activities</a>
              </li>
              <li class="nav-item  item-6">
                <a class="nav-link active ">ListYorShows</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active ">Corporate</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active ">Offers</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active ">GiftCards</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>

Todoproject/Todoproject/templates/registeruser.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div>
        <input type="text" placeholder="first name" name="fname">
    </div>
    <div>
        <input type="text" placeholder="last name" name="lname">
    </div>
    <div>
        <input type="text" placeholder="email" name="email">
    </div>
    <div>
        <input type="text" placeholder="username" name="username">
    </div>
    <div>
        <input type="text" placeholder="password" name="password">
    </div>
    <div>
        <input type="text" placeholder="confirm password" name="cpassword">
    </div>
    <div>
        <button>submit</button>
    </div>
</form>

{% endblock %}

Todoproject/Todoproject/templates/update.html
{% extends 'base.html' %}
    {% block content %}
    <div class="container">
        <form class="border mt-5 mb-2" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <input class="form-control mb-2" type="text" name="name" placeholder="Movie name" value="{{movies.name}}">
    
            <input class="form-control mb-2" type="number" name="rate" placeholder="Rate" value="{{movies.rate}}">
    
            <input class="form-control mb-2" type="text" name="screen" placeholder="Screen" value="{{movies.screen}}">
    
            <input class="form-control mb-2" type="text" name="language" placeholder="Language" value="{{movies.language}}">
    
            <input class="form-control mb-2" type="number" name="duration" placeholder="Duration" value="{{movies.duration}}">
    
            <input class="form-control mb-2" type="text" name="category" placeholder="Category" value="{{movies.category}}">
    
            <input class="form-control mb-2" type="text" name="certification" placeholder="certification" value="{{movies.certification}}">
    
            <input class="form-control mb-2" type="date" name="date" placeholder="Releas date" value="{{movies.date}}">
    
            <input class="form-control mb-2" type="file" name="image" placeholder="Poster">
    
            <input class="form-control mb-2" type="file" name="banner" placeholder="Banner">
    
            <input class="form-control mb-2" type="text" name="description" placeholder="Description" value="{{movies.description}}">
            
            <button class="btn btn-success mb-3 mt-3" style="margin-left: 450px;">Update</button>
        </form>  
{% endblock %}